-- ------------------------------------------------------------------
-- Update alamat & tahun_lulus kandidat (data dummy otomatis)
--   alamat       : cycle 20 daerah Bekasi/Jakarta/Depok/Bogor
--   tahun_lulus  : tahun_lahir + 18 (lulus SMK ~ usia 18)
-- Jalankan sekali di database yang sudah ada datanya.
-- ------------------------------------------------------------------

UPDATE tb_kandidat SET alamat = 'Jl. Mawar Merah No. 12, Bojong Rawalumbu, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A1';
UPDATE tb_kandidat SET alamat = 'Jl. Melati Indah No. 8, Pondok Gede, Bekasi', tahun_lulus = 2019 WHERE nisn = 'A2';
UPDATE tb_kandidat SET alamat = 'Jl. Anggrek Blok C-15, Jatiasih, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A3';
UPDATE tb_kandidat SET alamat = 'Jl. Kenanga Raya No. 22, Bekasi Barat, Bekasi', tahun_lulus = 2017 WHERE nisn = 'A4';
UPDATE tb_kandidat SET alamat = 'Jl. Flamboyan No. 5, Rawalumbu, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A5';
UPDATE tb_kandidat SET alamat = 'Jl. Cendana No. 10, Bekasi Selatan, Bekasi', tahun_lulus = 2015 WHERE nisn = 'A6';
UPDATE tb_kandidat SET alamat = 'Jl. Diponegoro No. 17, Cakung, Jakarta Timur', tahun_lulus = 2021 WHERE nisn = 'A7';
UPDATE tb_kandidat SET alamat = 'Jl. Sudirman Kav. 3, Jatinegara, Jakarta Timur', tahun_lulus = 2021 WHERE nisn = 'A8';
UPDATE tb_kandidat SET alamat = 'Jl. Imam Bonjol No. 9, Matraman, Jakarta Timur', tahun_lulus = 2020 WHERE nisn = 'A9';
UPDATE tb_kandidat SET alamat = 'Jl. Kartini No. 14, Kelapa Gading, Jakarta Utara', tahun_lulus = 2019 WHERE nisn = 'A10';
UPDATE tb_kandidat SET alamat = 'Jl. Pahlawan Revolusi No. 7, Cibinong, Bogor', tahun_lulus = 2019 WHERE nisn = 'A11';
UPDATE tb_kandidat SET alamat = 'Jl. Cempaka Putih No. 11, Beji, Depok', tahun_lulus = 2019 WHERE nisn = 'A12';
UPDATE tb_kandidat SET alamat = 'Jl. Dahlia No. 4, Sukmajaya, Depok', tahun_lulus = 2021 WHERE nisn = 'A13';
UPDATE tb_kandidat SET alamat = 'Jl. Tulip No. 19, Bantar Gebang, Bekasi', tahun_lulus = 2018 WHERE nisn = 'A14';
UPDATE tb_kandidat SET alamat = 'Jl. Bougenville No. 6, Jatisampurna, Bekasi', tahun_lulus = 2013 WHERE nisn = 'A15';
UPDATE tb_kandidat SET alamat = 'Jl. Seroja No. 13, Cimanggis, Depok', tahun_lulus = 2021 WHERE nisn = 'A16';
UPDATE tb_kandidat SET alamat = 'Jl. Wijaya Kusuma No. 21, Cilincing, Jakarta Utara', tahun_lulus = 2015 WHERE nisn = 'A17';
UPDATE tb_kandidat SET alamat = 'Jl. Kamboja No. 18, Pondok Melati, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A18';
UPDATE tb_kandidat SET alamat = 'Jl. Teratai No. 25, Duren Sawit, Jakarta Timur', tahun_lulus = 2019 WHERE nisn = 'A19';
UPDATE tb_kandidat SET alamat = 'Jl. Sakura No. 2, Mustika Jaya, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A20';
UPDATE tb_kandidat SET alamat = 'Jl. Mawar Merah No. 12, Bojong Rawalumbu, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A21';
UPDATE tb_kandidat SET alamat = 'Jl. Melati Indah No. 8, Pondok Gede, Bekasi', tahun_lulus = 2019 WHERE nisn = 'A22';
UPDATE tb_kandidat SET alamat = 'Jl. Anggrek Blok C-15, Jatiasih, Bekasi', tahun_lulus = 2019 WHERE nisn = 'A23';
UPDATE tb_kandidat SET alamat = 'Jl. Kenanga Raya No. 22, Bekasi Barat, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A24';
UPDATE tb_kandidat SET alamat = 'Jl. Flamboyan No. 5, Rawalumbu, Bekasi', tahun_lulus = 2017 WHERE nisn = 'A25';
UPDATE tb_kandidat SET alamat = 'Jl. Cendana No. 10, Bekasi Selatan, Bekasi', tahun_lulus = 2015 WHERE nisn = 'A26';
UPDATE tb_kandidat SET alamat = 'Jl. Diponegoro No. 17, Cakung, Jakarta Timur', tahun_lulus = 2015 WHERE nisn = 'A27';
UPDATE tb_kandidat SET alamat = 'Jl. Sudirman Kav. 3, Jatinegara, Jakarta Timur', tahun_lulus = 2020 WHERE nisn = 'A28';
UPDATE tb_kandidat SET alamat = 'Jl. Imam Bonjol No. 9, Matraman, Jakarta Timur', tahun_lulus = 2022 WHERE nisn = 'A29';
UPDATE tb_kandidat SET alamat = 'Jl. Kartini No. 14, Kelapa Gading, Jakarta Utara', tahun_lulus = 2019 WHERE nisn = 'A30';
UPDATE tb_kandidat SET alamat = 'Jl. Pahlawan Revolusi No. 7, Cibinong, Bogor', tahun_lulus = 2021 WHERE nisn = 'A31';
UPDATE tb_kandidat SET alamat = 'Jl. Cempaka Putih No. 11, Beji, Depok', tahun_lulus = 2017 WHERE nisn = 'A32';
UPDATE tb_kandidat SET alamat = 'Jl. Dahlia No. 4, Sukmajaya, Depok', tahun_lulus = 2017 WHERE nisn = 'A33';
UPDATE tb_kandidat SET alamat = 'Jl. Tulip No. 19, Bantar Gebang, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A34';
UPDATE tb_kandidat SET alamat = 'Jl. Bougenville No. 6, Jatisampurna, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A35';
UPDATE tb_kandidat SET alamat = 'Jl. Seroja No. 13, Cimanggis, Depok', tahun_lulus = 2020 WHERE nisn = 'A36';
UPDATE tb_kandidat SET alamat = 'Jl. Wijaya Kusuma No. 21, Cilincing, Jakarta Utara', tahun_lulus = 2022 WHERE nisn = 'A37';
UPDATE tb_kandidat SET alamat = 'Jl. Kamboja No. 18, Pondok Melati, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A38';
UPDATE tb_kandidat SET alamat = 'Jl. Teratai No. 25, Duren Sawit, Jakarta Timur', tahun_lulus = 2019 WHERE nisn = 'A39';
UPDATE tb_kandidat SET alamat = 'Jl. Sakura No. 2, Mustika Jaya, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A40';
UPDATE tb_kandidat SET alamat = 'Jl. Mawar Merah No. 12, Bojong Rawalumbu, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A41';
UPDATE tb_kandidat SET alamat = 'Jl. Melati Indah No. 8, Pondok Gede, Bekasi', tahun_lulus = 2017 WHERE nisn = 'A42';
UPDATE tb_kandidat SET alamat = 'Jl. Anggrek Blok C-15, Jatiasih, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A43';
UPDATE tb_kandidat SET alamat = 'Jl. Kenanga Raya No. 22, Bekasi Barat, Bekasi', tahun_lulus = 2018 WHERE nisn = 'A44';
UPDATE tb_kandidat SET alamat = 'Jl. Flamboyan No. 5, Rawalumbu, Bekasi', tahun_lulus = 2017 WHERE nisn = 'A45';
UPDATE tb_kandidat SET alamat = 'Jl. Cendana No. 10, Bekasi Selatan, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A46';
UPDATE tb_kandidat SET alamat = 'Jl. Diponegoro No. 17, Cakung, Jakarta Timur', tahun_lulus = 2012 WHERE nisn = 'A47';
UPDATE tb_kandidat SET alamat = 'Jl. Sudirman Kav. 3, Jatinegara, Jakarta Timur', tahun_lulus = 2018 WHERE nisn = 'A48';
UPDATE tb_kandidat SET alamat = 'Jl. Imam Bonjol No. 9, Matraman, Jakarta Timur', tahun_lulus = 2017 WHERE nisn = 'A49';
UPDATE tb_kandidat SET alamat = 'Jl. Kartini No. 14, Kelapa Gading, Jakarta Utara', tahun_lulus = 2019 WHERE nisn = 'A50';
UPDATE tb_kandidat SET alamat = 'Jl. Pahlawan Revolusi No. 7, Cibinong, Bogor', tahun_lulus = 2015 WHERE nisn = 'A51';
UPDATE tb_kandidat SET alamat = 'Jl. Cempaka Putih No. 11, Beji, Depok', tahun_lulus = 2021 WHERE nisn = 'A52';
UPDATE tb_kandidat SET alamat = 'Jl. Dahlia No. 4, Sukmajaya, Depok', tahun_lulus = 2022 WHERE nisn = 'A53';
UPDATE tb_kandidat SET alamat = 'Jl. Tulip No. 19, Bantar Gebang, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A54';
UPDATE tb_kandidat SET alamat = 'Jl. Bougenville No. 6, Jatisampurna, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A55';
UPDATE tb_kandidat SET alamat = 'Jl. Seroja No. 13, Cimanggis, Depok', tahun_lulus = 2021 WHERE nisn = 'A56';
UPDATE tb_kandidat SET alamat = 'Jl. Wijaya Kusuma No. 21, Cilincing, Jakarta Utara', tahun_lulus = 2019 WHERE nisn = 'A57';
UPDATE tb_kandidat SET alamat = 'Jl. Kamboja No. 18, Pondok Melati, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A58';
UPDATE tb_kandidat SET alamat = 'Jl. Teratai No. 25, Duren Sawit, Jakarta Timur', tahun_lulus = 2016 WHERE nisn = 'A59';
UPDATE tb_kandidat SET alamat = 'Jl. Sakura No. 2, Mustika Jaya, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A60';
UPDATE tb_kandidat SET alamat = 'Jl. Mawar Merah No. 12, Bojong Rawalumbu, Bekasi', tahun_lulus = 2017 WHERE nisn = 'A61';
UPDATE tb_kandidat SET alamat = 'Jl. Melati Indah No. 8, Pondok Gede, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A62';
UPDATE tb_kandidat SET alamat = 'Jl. Anggrek Blok C-15, Jatiasih, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A63';
UPDATE tb_kandidat SET alamat = 'Jl. Kenanga Raya No. 22, Bekasi Barat, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A64';
UPDATE tb_kandidat SET alamat = 'Jl. Flamboyan No. 5, Rawalumbu, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A65';
UPDATE tb_kandidat SET alamat = 'Jl. Cendana No. 10, Bekasi Selatan, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A66';
UPDATE tb_kandidat SET alamat = 'Jl. Diponegoro No. 17, Cakung, Jakarta Timur', tahun_lulus = 2016 WHERE nisn = 'A67';
UPDATE tb_kandidat SET alamat = 'Jl. Sudirman Kav. 3, Jatinegara, Jakarta Timur', tahun_lulus = 2019 WHERE nisn = 'A68';
UPDATE tb_kandidat SET alamat = 'Jl. Imam Bonjol No. 9, Matraman, Jakarta Timur', tahun_lulus = 2021 WHERE nisn = 'A69';
UPDATE tb_kandidat SET alamat = 'Jl. Kartini No. 14, Kelapa Gading, Jakarta Utara', tahun_lulus = 2020 WHERE nisn = 'A70';
UPDATE tb_kandidat SET alamat = 'Jl. Pahlawan Revolusi No. 7, Cibinong, Bogor', tahun_lulus = 2022 WHERE nisn = 'A71';
UPDATE tb_kandidat SET alamat = 'Jl. Cempaka Putih No. 11, Beji, Depok', tahun_lulus = 2016 WHERE nisn = 'A72';
UPDATE tb_kandidat SET alamat = 'Jl. Dahlia No. 4, Sukmajaya, Depok', tahun_lulus = 2022 WHERE nisn = 'A73';
UPDATE tb_kandidat SET alamat = 'Jl. Tulip No. 19, Bantar Gebang, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A74';
UPDATE tb_kandidat SET alamat = 'Jl. Bougenville No. 6, Jatisampurna, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A75';
UPDATE tb_kandidat SET alamat = 'Jl. Seroja No. 13, Cimanggis, Depok', tahun_lulus = 2020 WHERE nisn = 'A76';
UPDATE tb_kandidat SET alamat = 'Jl. Wijaya Kusuma No. 21, Cilincing, Jakarta Utara', tahun_lulus = 2019 WHERE nisn = 'A77';
UPDATE tb_kandidat SET alamat = 'Jl. Kamboja No. 18, Pondok Melati, Bekasi', tahun_lulus = 2023 WHERE nisn = 'A78';
UPDATE tb_kandidat SET alamat = 'Jl. Teratai No. 25, Duren Sawit, Jakarta Timur', tahun_lulus = 2018 WHERE nisn = 'A79';
UPDATE tb_kandidat SET alamat = 'Jl. Sakura No. 2, Mustika Jaya, Bekasi', tahun_lulus = 2018 WHERE nisn = 'A80';
UPDATE tb_kandidat SET alamat = 'Jl. Mawar Merah No. 12, Bojong Rawalumbu, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A81';
UPDATE tb_kandidat SET alamat = 'Jl. Melati Indah No. 8, Pondok Gede, Bekasi', tahun_lulus = 2018 WHERE nisn = 'A82';
UPDATE tb_kandidat SET alamat = 'Jl. Anggrek Blok C-15, Jatiasih, Bekasi', tahun_lulus = 2013 WHERE nisn = 'A83';
UPDATE tb_kandidat SET alamat = 'Jl. Kenanga Raya No. 22, Bekasi Barat, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A84';
UPDATE tb_kandidat SET alamat = 'Jl. Flamboyan No. 5, Rawalumbu, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A85';
UPDATE tb_kandidat SET alamat = 'Jl. Cendana No. 10, Bekasi Selatan, Bekasi', tahun_lulus = 2018 WHERE nisn = 'A86';
UPDATE tb_kandidat SET alamat = 'Jl. Diponegoro No. 17, Cakung, Jakarta Timur', tahun_lulus = 2020 WHERE nisn = 'A87';
UPDATE tb_kandidat SET alamat = 'Jl. Sudirman Kav. 3, Jatinegara, Jakarta Timur', tahun_lulus = 2019 WHERE nisn = 'A88';
UPDATE tb_kandidat SET alamat = 'Jl. Imam Bonjol No. 9, Matraman, Jakarta Timur', tahun_lulus = 2020 WHERE nisn = 'A89';
UPDATE tb_kandidat SET alamat = 'Jl. Kartini No. 14, Kelapa Gading, Jakarta Utara', tahun_lulus = 2021 WHERE nisn = 'A90';
UPDATE tb_kandidat SET alamat = 'Jl. Pahlawan Revolusi No. 7, Cibinong, Bogor', tahun_lulus = 2021 WHERE nisn = 'A91';
UPDATE tb_kandidat SET alamat = 'Jl. Cempaka Putih No. 11, Beji, Depok', tahun_lulus = 2022 WHERE nisn = 'A92';
UPDATE tb_kandidat SET alamat = 'Jl. Dahlia No. 4, Sukmajaya, Depok', tahun_lulus = 2022 WHERE nisn = 'A93';
UPDATE tb_kandidat SET alamat = 'Jl. Tulip No. 19, Bantar Gebang, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A94';
UPDATE tb_kandidat SET alamat = 'Jl. Bougenville No. 6, Jatisampurna, Bekasi', tahun_lulus = 2021 WHERE nisn = 'A95';
UPDATE tb_kandidat SET alamat = 'Jl. Seroja No. 13, Cimanggis, Depok', tahun_lulus = 2021 WHERE nisn = 'A96';
UPDATE tb_kandidat SET alamat = 'Jl. Wijaya Kusuma No. 21, Cilincing, Jakarta Utara', tahun_lulus = 2020 WHERE nisn = 'A97';
UPDATE tb_kandidat SET alamat = 'Jl. Kamboja No. 18, Pondok Melati, Bekasi', tahun_lulus = 2020 WHERE nisn = 'A98';
UPDATE tb_kandidat SET alamat = 'Jl. Teratai No. 25, Duren Sawit, Jakarta Timur', tahun_lulus = 2022 WHERE nisn = 'A99';
UPDATE tb_kandidat SET alamat = 'Jl. Sakura No. 2, Mustika Jaya, Bekasi', tahun_lulus = 2022 WHERE nisn = 'A100';

-- Verifikasi (semua baris harusnya gak NULL):
-- SELECT nisn, nama, tanggal_lahir, tahun_lulus, alamat FROM tb_kandidat ORDER BY nisn LIMIT 10;
